### PR TITLE
TEE driver update to 94a3ae7

### PR DESCRIPTION
**Pull request by vchong**

### CODE REVIEW

**Comment by vchong** [comment]
@jenswi-linaro @jbech-linaro fyi

**Comment by jockebech** [comment]
@vchong , seems like this has been pending for a while, who would be the person merging this? Fathi? Amit?

**Comment by fboudra** [comment]
@LGraemeG @broonie are the maintainers. Users should submit pull request by email to rp-enterprise@linaro.org

**Comment by fboudra** [comment]
Per @vchong request, closing. He was interested to get OP-TEE running on HiKey/HiKey960, but RPK isn't used for these builds.

**Pull request closed without merging**
