### PR TITLE
Rpk v4.14 meltdown spectre mitigations

### PR DESCRIPTION
**Pull request by ardbiesheuvel**
This is a backport to RPK/v4.14 of the KPTI patches that are queued for v4.16 in the arm64 tree, as well as the HYP branch predictor hardening patches that were sent to LAKML over the past week, including one for Falkor that is built on top of the new BP hardening framework.

Note that this makes KPTI dependent on a newly introduced ID register that defaults to 'affected' for all CPUs, including ones that are known not to be affected by the variant that KPTI addresses (Meltdown). This is in line with the upstream, and KPTI can still be disabled both at build time and at runtime.

### CODE REVIEW

**Comment by ndechesne** [comment]
hi @ardbiesheuvel , i would like to include an up-to-date patchset for this issue in our Dragonboard Linux release, and I have just noticed this PR from you. Our releases are also based on 4.14, do you think i should safely take all patches from this patch series and be done? is anyone at linaro planning to maintain a 'dev' branch with the backport (at least until it gets merged/backported in LTS)?

**Comment by ardbiesheuvel** [comment]
On 8 January 2018 at 20:30, Nicolas Dechesne <notifications@github.com>
wrote:

> hi @ardbiesheuvel <https://github.com/ardbiesheuvel> , i would like to
> include an up-to-date patchset for this issue in our Dragonboard Linux
> release, and I have just noticed this PR from you. Our releases are also
> based on 4.14, do you think i should safely take all patches from this
> patch series and be done? is anyone at linaro planning to maintain a 'dev'
> branch with the backport (at least until it gets merged/backported in LTS)?
>
>
​Please ignore that pull request for now. I am aligning with the arm64
maintainers to create a v4.14 backport that is also suitable for upstream
v4.14 LTS, rather than something that is only suitable for RPK

I am currently working on it, and should have something to share by
tomorrow.

Thanks,
Ard.
​

**Comment by ndechesne** [comment]
ok, that seems even better!

**Comment by ardbiesheuvel** [comment]
On 8 January 2018 at 20:36, Nicolas Dechesne <notifications@github.com>
wrote:

> ok, that seems even better!
>

​There are some stability issues with the patches so we'll need to hold off
for a bit.
​

**Pull request closed without merging**
